### ISSUE TITLE
New encoding for template config_templates

### ISSUE THREAD

**Issue by puria** [ForkbombEu/credimi#274]
the new format should be, that passe a `string` to the `credimi` function in forma of a json

```yaml
---
variant:
  credential_format: iso_mdl
  client_id_scheme: did
  request_method: request_uri_signed
  response_mode: direct_post.jwt
form:
  alias: |>
    {{ 
      credimi \"
        {
          "credimi_id": "iso_mdl_did_request_uri_signed_direct_post_jwt_oid_alias",
          "field_id": "testalias",
          "field_label": "i18n_testalias"
          "field_description": "i18n_testalias_description"
          "field_default_value": uuidv4
          "field_type": "string"
          "field_options": []
        }
    \"}}
  server:
    authorization_endpoint: openid-vc://

```
